USER_NAME = holykeebs

POINTING_DEVICE ?= trackball_trackpoint
SIDE ?= right
TRACKBALL_RGB_RAINBOW = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
AUTOCORRECT_ENABLE = yes

QMK_SETTINGS = no

OPT_DEFS += -DHK_PERIPHERAL_DEFAULT_POINTER_SCROLL_BUFFER_SIZE=5

AUTO_SHIFT_ENABLE = no
